apiVersion: v1
kind: Pod
metadata:
  name: pod-with-hostpath-pvc
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: data-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: data-volume
    type: pvc
    claimName: pvc-hostpath-static
