apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-volume-pod1
  namespace: default
  labels:
    app: volume-test
    role: pod1
    test: volume-mount
spec:
  volumes:
  - name: test-volume
    hostPath:
      path: /tmp/minik8s-volume-test
      type: DirectoryOrCreate
  containers:
  - name: ubuntu-container1
    image: ubuntu:latest
    command: ["bash", "-c"]
    args: [
      "apt-get update && apt-get install -y vim curl procps &&
       echo 'Pod1 started at $(date)' > /volume/pod1-startup.log &&
       echo 'Pod1 hostname: $(hostname)' >> /volume/pod1-info.txt &&
       echo 'Pod1 process info:' >> /volume/pod1-info.txt &&
       ps aux >> /volume/pod1-info.txt &&
       while true; do
         echo '[$(date)] Pod1 heartbeat - Writing to shared volume' >> /volume/pod1-heartbeat.log;
         echo 'Current files in volume:' >> /volume/pod1-heartbeat.log;
         ls -la /volume/ >> /volume/pod1-heartbeat.log;
         echo '--- End of Pod1 heartbeat ---' >> /volume/pod1-heartbeat.log;
         sleep 60;
       done"
    ]
    volumeMounts:
    - name: test-volume
      mountPath: /volume
      readOnly: false
    resources:
      requests:
        cpu: 0.1
        memory: 128Mi
      limits:
        cpu: 0.5
        memory: 256Mi
