apiVersion: v1
kind: Service
metadata:
  name: enhanced-nodeport-service
  namespace: default
  labels:
    app: hello-world
    environment: production
spec:
  type: NodePort
  selector:
    app: hello-world
  ports:
  - name: http
    port: 80
    targetPort: 9090
    protocol: TCP
    nodePort: 30080  # 指定NodePort端口
