apiVersion: v1
kind: Pod
metadata:
  name: my-security-pod
  namespace: default
  labels:
    app: myapp
spec:
  securityContext: # Pod-level security context
    runAsUser: 1000
    runAsGroup: 2000
    fsGroup: 3000 # This will be stored but not directly applied by Docker SDK
    supplementalGroups: [4000, 5000]
    privileged: false # Should be overridden by container if true

  containers:
  - name: my-container-1
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    securityContext: # Container-level security context (overrides Pod-level)
      runAsUser: 1001
      runAsGroup: 2001
      capabilities:
        add: ["NET_ADMIN", "SYS_TIME"]
        drop: ["MKNOD"]
  - name: my-container-2
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    securityContext: # Another container, inherits some, overrides some
      readOnlyRootFilesystem: true
      privileged: true # This should make it privileged
      supplementalGroups: [6000] # This should merge/add

apiVersion: v1
kind: Pod
metadata:
  name: test-security-context
  namespace: default
  labels:
    app: myapp
    server: "1"
spec:
  securityContext: # Pod-level security context
    runAsUser: 1000
    runAsGroup: 2000
    fsGroup: 3000 # This will be stored but not directly applied by Docker SDK
    supplementalGroups: [4000, 5000]
    privileged: false # Should be overridden by container if true

  containers:
  - name: test-server-container-1
    image: registry.cn-hangzhou.aliyuncs.com/tanjunchen/network-multitool:v1
    command: ["sh", "-c"]
    args: ["echo 'Starting server 1 on port 9090...' && while true; do echo -e 'HTTP/1.1 200 OK\\r\\nContent-Type: text/plain\\r\\nContent-Length: 31\\r\\n\\r\\nResponse from SERVER-1 (Pod 1)' | nc -l -p 9090; done"]
    ports:
    - containerPort: 9090
      protocol: TCP
    resources:
      requests:
        cpu: 1
        memory: 134217728
      limits:
        cpu: 2
        memory: 268435456
        
    securityContext: # Container-level security context (overrides Pod-level)
      runAsUser: 1001
      runAsGroup: 2001
      capabilities:
        add: ["NET_ADMIN", "SYS_TIME"]
        drop: ["MKNOD"]
